print("what is your name?")
name = input()
print (name)
print("what is your email?")
email = input()
print("What is your department?")
contact=input()
print("What is your Access tier?")
access_tier=input()
print("+--------------------------------------------------+")
print("|---------------apex entertainmnet pass------------|")
print("|--------------------------------------------------|")
print("|ATTENDEEE :" + name.ljust(39)+ "|")
print("|--------------------------------------------------|")
print("|EMAIL :" + email.ljust(43)+ "|")
print("|--------------------------------------------------|")
print("|ORG :" + contact.ljust(45)+ "|")
print("|--------------------------------------------------|")
print("|ACCESS TIER :" + access_tier.ljust(37)+ "|")
print("+--------------------------------------------------+")