print("what is your name?")
name = input()
print (name)
print("what is your email?")
email = input()
print("+--------------------------------------------------+")
print("|---------------apex entertainmnet pass------------|")
print("|--------------------------------------------------|")
print("|ATTENDEEE :" + name.ljust(39)+ "|")
print("|--------------------------------------------------|")